blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/VerburgtJimmy/vellum/discussions/categories/q-a
    about: Ask a question in Discussions (Q&A)
  - name: Idea
    url: https://github.com/VerburgtJimmy/vellum/discussions/categories/ideas
    about: Suggest an idea in Discussions
